import { env } from "@/env";

export enum PRICING {
  BASIC_MONTHLY = "BASIC_MONTHLY",
  PLUS_MONTHLY = "PLUS_MONTHLY",
  BASIC_YEARLY = "BASIC_YEARLY",
  PLUS_YEARLY = "PLUS_YEARLY",
}

export const STRIPE_PRICES = {
  [PRICING.BASIC_MONTHLY]: env.NEXT_PUBLIC_STRIPE_BASIC_MONTHLY_PRICE_ID,
  [PRICING.PLUS_MONTHLY]: env.NEXT_PUBLIC_STRIPE_PLUS_MONTHLY_PRICE_ID,
  [PRICING.BASIC_YEARLY]: env.NEXT_PUBLIC_STRIPE_BASIC_YEARLY_PRICE_ID,
  [PRICING.PLUS_YEARLY]: env.NEXT_PUBLIC_STRIPE_PLUS_YEARLY_PRICE_ID,
} as const;
